name: Build and Upload Artifact

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        container:
            image: debian:bookworm

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Checkout submodules
          uses: actions/checkout@v2
          with:
            submodules: true
        
        - name: Install dependencies
          run: |
                apt-get update
                apt-get install -y glslang-dev glslang-tools graphviz libgbm-dev libinput-dev libudev-dev libvulkan-dev libxcb-composite0-dev libxcb-dri3-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-present-dev libxcb-render-util0-dev libxcb-res0-dev libxcb-xinput-dev libxkbcommon-dev meson plantuml xmlto xsltproc wayland-protocols libwlroots-dev doxygen

        - name: Build
          run: |
               mkdir build
               cd build
               cmake ..
               make -j
               make install DESTDIR=appdir
               zip -r ../appdir.zip appdir

        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
              name: appdir
              path: appdir.zip
